// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getmaxEigenValue
double getmaxEigenValue(arma::mat M);
RcppExport SEXP _pRoxgrad_getmaxEigenValue(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getmaxEigenValue(M));
    return rcpp_result_gen;
END_RCPP
}
// shrink_groupcpp
arma::mat shrink_groupcpp(arma::mat A, arma::mat g_idx);
RcppExport SEXP _pRoxgrad_shrink_groupcpp(SEXP ASEXP, SEXP g_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g_idx(g_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(shrink_groupcpp(A, g_idx));
    return rcpp_result_gen;
END_RCPP
}
// cal2normcpp
double cal2normcpp(arma::mat A, arma::mat g_idx);
RcppExport SEXP _pRoxgrad_cal2normcpp(SEXP ASEXP, SEXP g_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g_idx(g_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(cal2normcpp(A, g_idx));
    return rcpp_result_gen;
END_RCPP
}
// soft_thresholdingcpp
arma::mat soft_thresholdingcpp(arma::mat v, double lambdaL);
RcppExport SEXP _pRoxgrad_soft_thresholdingcpp(SEXP vSEXP, SEXP lambdaLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type lambdaL(lambdaLSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_thresholdingcpp(v, lambdaL));
    return rcpp_result_gen;
END_RCPP
}
// SPGcpp
List SPGcpp(arma::mat X, arma::mat Y, arma:: mat XX, arma:: mat XY, int J, double gamma, double lambda, double CNorm, double mu, arma::sp_mat C, arma::mat w, arma::mat g_idx, double L, double theta, arma::mat beta, int maxiter, int display_iter, int N, double tol);
RcppExport SEXP _pRoxgrad_SPGcpp(SEXP XSEXP, SEXP YSEXP, SEXP XXSEXP, SEXP XYSEXP, SEXP JSEXP, SEXP gammaSEXP, SEXP lambdaSEXP, SEXP CNormSEXP, SEXP muSEXP, SEXP CSEXP, SEXP wSEXP, SEXP g_idxSEXP, SEXP LSEXP, SEXP thetaSEXP, SEXP betaSEXP, SEXP maxiterSEXP, SEXP display_iterSEXP, SEXP NSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma:: mat >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< arma:: mat >::type XY(XYSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type CNorm(CNormSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g_idx(g_idxSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type display_iter(display_iterSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(SPGcpp(X, Y, XX, XY, J, gamma, lambda, CNorm, mu, C, w, g_idx, L, theta, beta, maxiter, display_iter, N, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pRoxgrad_getmaxEigenValue", (DL_FUNC) &_pRoxgrad_getmaxEigenValue, 1},
    {"_pRoxgrad_shrink_groupcpp", (DL_FUNC) &_pRoxgrad_shrink_groupcpp, 2},
    {"_pRoxgrad_cal2normcpp", (DL_FUNC) &_pRoxgrad_cal2normcpp, 2},
    {"_pRoxgrad_soft_thresholdingcpp", (DL_FUNC) &_pRoxgrad_soft_thresholdingcpp, 2},
    {"_pRoxgrad_SPGcpp", (DL_FUNC) &_pRoxgrad_SPGcpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_pRoxgrad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
