# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

one <- function() {
    .Call(`_pRoxgrad_one`)
}

signC <- function(x) {
    .Call(`_pRoxgrad_signC`, x)
}

sumC <- function(x) {
    .Call(`_pRoxgrad_sumC`, x)
}

meanC <- function(x) {
    .Call(`_pRoxgrad_meanC`, x)
}

getEigenValues <- function(M) {
    .Call(`_pRoxgrad_getEigenValues`, M)
}

shrink_groupcpp <- function(C, g_idx) {
    .Call(`_pRoxgrad_shrink_groupcpp`, C, g_idx)
}

cal2normcpp <- function(A, g_idx) {
    .Call(`_pRoxgrad_cal2normcpp`, A, g_idx)
}

soft_thresholding <- function(v, lambdaL) {
    .Call(`_pRoxgrad_soft_thresholding`, v, lambdaL)
}

SPGcpp <- function(X, Y, J, gamma, lambda, Cnorm, mu, C, w, g_idx, theta, beta, maxiter, display_iter, N, tol) {
    .Call(`_pRoxgrad_SPGcpp`, X, Y, J, gamma, lambda, Cnorm, mu, C, w, g_idx, theta, beta, maxiter, display_iter, N, tol)
}

cal2normcpp <- function(A, g_idx) {
    .Call(`_pRoxgrad_cal2normcpp`, A, g_idx)
}

soft_thresholding <- function(v, lambdaL) {
    .Call(`_pRoxgrad_soft_thresholding`, v, lambdaL)
}

timesTwo <- function(x) {
    .Call(`_pRoxgrad_timesTwo`, x)
}

