# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

one <- function() {
    .Call(`_pRoxgrad_one`)
}

signC <- function(x) {
    .Call(`_pRoxgrad_signC`, x)
}

sumC <- function(x) {
    .Call(`_pRoxgrad_sumC`, x)
}

meanC <- function(x) {
    .Call(`_pRoxgrad_meanC`, x)
}

rcpp_hello_world <- function() {
    .Call(`_pRoxgrad_rcpp_hello_world`)
}

soft_thresholding <- function(v, lambdaL) {
    .Call(`_pRoxgrad_soft_thresholding`, v, lambdaL)
}

timesTwo <- function(x) {
    .Call(`_pRoxgrad_timesTwo`, x)
}

